<BluetoothRunScreen>:
    orientation: 'vertical'
    padding: dp(10)

    Widget:
        size_hint_y: None
        height: dp(40)

    MDLabel:
        text: root.title
        halign: 'center'
        font_style: 'Headline'
        size_hint_y: None
        padding_y: dp(20)
        height: dp(40)

    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'center'
        MDCircularProgressIndicator:
            size_hint: (.4, .4)
            line_width: dp(5)
