#:import CustomButton ui.button.CustomButton

<MainMenu>:
    orientation: "vertical"
    Label:
        text: "Rubik's Cube Master"
        color: "#3F3F3F"
        size_hint: 1, 0.2
        font_size: root.width / 15
    Label:
        text: root.text
        color: "#3F3F3F"
        size_hint: 1, 0.6
        text_size: self.size
    CustomButton:
        text: "Popup"
        size_hint: 1, 0.2
        border_radius: 15, 15, 0, 0
        on_release: root.popup.open()
